services:
  workspace:
    container_name: side_project_devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: side_project_devcontainer:local
    command: sleep infinity

    ports:
      - "5173:5173" # 프론트엔드 (Vite 개발 서버)
      - "18080:8091" # 백엔드 (Java 개발 서버)

    environment:
      TZ: Asia/Seoul

    volumes:
      - ..:${containerWorkspaceFolder}:cached

    networks:
      - side_project_network

    # depends_on:
    #   - db

networks:
  side_project_network:
    # external: true
    driver: bridge # 같은 이름의 네트워크는 자동 merge
